#!/usr/bin/env bash
# Configure the container to run Nginx as the nginx user.
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen .*/listen 8080;/' /etc/nginx/sites-available/default
pkill apache2
service nginx restart
