#!/usr/bin/env bash
# Configure Nginx to run as nginx user on port 8080
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
pkill apache2
service nginx restart

